USE SuperStoreDB;

DROP VIEW IF EXISTS Staging_SuperStoreSource_V;

CREATE VIEW Staging_SuperStoreSource_V 
AS
SELECT
	T.ROW_ID				AS ROW_ID,
	T.ORDER_ID				AS ORDER_ID,
	T.ORDER_DATE			AS ORDER_DATE,
	T.SHIP_DATE				AS SHIP_DATE,
	T.SHIP_MODE				AS SHIP_MODE,
	T.CUSTOMER_NAME			AS CUSTOMER_NAME,
	T.SEGMENT				AS SEGMENT,
	T.[STATE]				AS [STATE],
	T.COUNTRY				AS COUNTRY,
	T.MARKET				AS MARKET,
	T.REGION				AS REGION,
	T.PRODUCT_ID			AS PRODUCT_ID,
	T.CATEGORY				AS CATEGORY,
	T.SUB_CATEGORY			AS SUB_CATEGORY,
	T.PRODUCT_NAME			AS PRODUCT_NAME,
	T.SALES					AS SALES,
	T.QUANTITY				AS QUANTITY,
	T.DISCOUNT				AS DISCOUNT,
	T.PROFIT				AS PROFIT,
	T.SHIPPING_COST			AS SHIPPING_COST,
	T.ORDER_PRIORITY		AS ORDER_PRIORITY,
	T.[YEAR]				AS [YEAR]  
FROM Staging_SuperStoreSource_T AS T
;