dbt_projects:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: LAPTOP-MCNKFD7O
      database: DEV
      schema: dbo
      windows_login: True
      trust_cert: True