USE SuperStoreDB;

DROP TABLE IF EXISTS Staging_SuperStoreSource_T

CREATE TABLE Staging_SuperStoreSource_T (
	ROW_ID INT IDENTITY(1,1) PRIMARY KEY,
	ORDER_ID VARCHAR(255),
	ORDER_DATE DATE,
	SHIP_DATE DATE,
	SHIP_MODE VARCHAR(255),
	CUSTOMER_NAME VARCHAR(255),
	SEGMENT VARCHAR(255),
	[STATE] VARCHAR(255),
	COUNTRY VARCHAR(255),
	MARKET VARCHAR(255),
	REGION VARCHAR(255),
	PRODUCT_ID VARCHAR(255),
	CATEGORY VARCHAR(255),
	SUB_CATEGORY VARCHAR(255),
	PRODUCT_NAME VARCHAR(300),
	SALES VARCHAR(255),
	QUANTITY VARCHAR(255),
	DISCOUNT VARCHAR(255),
	PROFIT VARCHAR(255),
	SHIPPING_COST VARCHAR(255),
	ORDER_PRIORITY VARCHAR(255),
	[YEAR] VARCHAR(255),
	RecInsertTime DATE DEFAULT GetDate() NOT NULL
);