USE SuperStoreDB;

DROP TABLE IF EXISTS DimCountry_T; 

CREATE TABLE DimCountry_T(
	CountryID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Country_Name VARCHAR(255) NOT NULL,
	RegionID INT NOT NULL,
	RecInsertTime DEFAULT GetDate() NOT NULL, 
	CONSTRAINT FK_Region FOREIGN KEY (RegionID) REFERENCES DimRegion_T(RegionID)
);