USE SuperStoreDB;

DROP TABLE IF EXISTS DimMarket_T; 

CREATE TABLE DimMarket_T(
	MarketID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Market_Name VARCHAR(255) NOT NULL,
	RecInsertTime DEFAULT GetDate() NOT NULL 
);