CREATE TABLE STORE_DB.EMPLOYEE  
( 
EMP_ID 		NUMBER		 	NOT NULL,  
EMP_NAME 	VARCHAR2(255) 	NOT NULL,  
EMP_ADDR	VARCHAR2(255),
SALARY		NUMBER,
"VERSION" 	NUMBER 			NOT NULL, 
CONSTRAINT emp_pk PRIMARY KEY (EMP_ID)
);  