CREATE TABLE STORE_DB.EMPLOYEE  
( 
EMP_ID 		NUMBER		 	NOT NULL,  
EMP_NAME 	VARCHAR2(255) 	NOT NULL,  
EMP_ADDR	VARCHAR2(255),
SALARY		NUMBER,
"VERSION" 	NUMBER 			NOT NULL
);  

CREATE INDEX emp_id_i 
ON STORE_DB.EMPLOYEE(EMP_ID);