CREATE TABLE DEV_DB.EMPLOYEE_TGT  
( 
S_NO		NUMBER PRIMARY KEY NOT NULL,
EMP_ID 		NUMBER		 	NOT NULL,  
EMP_NAME 	VARCHAR2(255) 	NOT NULL,  
EMP_ADDR	VARCHAR2(255),
SALARY		NUMBER,
"VERSION" 	NUMBER 			NOT NULL
);  