-- 1. 
SELECT CITY, STATE FROM STATION;

-- 2.
SELECT DISTINCT(CITY) FROM STATION 
WHERE ((ID % 2) = 0);

-- 3.
SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION;

-- 4.
SELECT TOP 1 CITY, MAX(LEN(CITY)) AS LENG FROM STATION
GROUP BY CITY
ORDER BY LENG DESC;

SELECT TOP 1 CITY, MIN(LEN(CITY)) AS LENG FROM STATION
GROUP BY CITY
ORDER BY LENG ASC;

-- 5.
SELECT DISTINCT(CITY) FROM STATION
WHERE SUBSTRING(UPPER(CITY), 1, 1) IN ('A', 'E', 'I', 'O', 'U');

-- 6.
SELECT DISTINCT(CITY) FROM STATION
WHERE SUBSTRING(UPPER(CITY), LEN(CITY), 1) IN ('A', 'E', 'I', 'O', 'U');

-- 7.
SELECT DISTINCT(CITY) FROM STATION
WHERE SUBSTRING(UPPER(CITY), 1, 1) NOT IN ('A', 'E', 'I', 'O', 'U'); 

-- 8.
SELECT DISTINCT(CITY) FROM STATION
WHERE SUBSTRING(UPPER(CITY), LEN(CITY), 1) NOT IN ('A', 'E', 'I', 'O', 'U') 

-- 9.
SELECT DISTINCT CITY FROM STATION
WHERE SUBSTRING(UPPER(CITY), 1, 1) NOT IN ('A', 'E', 'I', 'O', 'U') OR 
SUBSTRING(UPPER(CITY), LEN(CITY), 1) NOT IN ('A', 'E', 'I', 'O', 'U');

-- 10.
SELECT DISTINCT CITY FROM STATION
WHERE SUBSTRING(UPPER(CITY), 1, 1) NOT IN ('A', 'I', 'E', 'O', 'U') AND
SUBSTRING(UPPER(CITY), LEN(CITY), 1) NOT IN ('A', 'I', 'E', 'O', 'U');